export default function MyHead() {
  return (
    <head>
      {/* Inter font */}
      <link
        rel="preload"
        href="/fonts/Inter/Inter-VariableFont_opsz,wght.ttf"
        as="font"
        type="font/ttf"
        crossOrigin="anonymous"
      />
      {/* Pretendard font */}
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Thin.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-ExtraLight.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Light.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Regular.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Medium.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-SemiBold.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Bold.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-ExtraBold.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Pretendard/Pretendard-Black.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />
    </head>
  )
}
